name: Telegram Bot Alert

on:
  workflow_dispatch:   # allows manual run
  schedule:
    - cron: "0 4 * * 1-5"   # runs every weekday at 9:30 AM IST (adjust if needed)

jobs:
  send_alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
